package StringConcat;


/**
* StringConcat/ConcatenatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcat.idl
* Monday, May 29, 2023 2:10:55 PM EDT
*/

public interface ConcatenatorOperations 
{
  String concatenate (String s1, String s2);
} // interface ConcatenatorOperations
