package StringConcat;

/**
* StringConcat/ConcatenatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcat.idl
* Monday, May 29, 2023 2:10:55 PM EDT
*/

public final class ConcatenatorHolder implements org.omg.CORBA.portable.Streamable
{
  public StringConcat.Concatenator value = null;

  public ConcatenatorHolder ()
  {
  }

  public ConcatenatorHolder (StringConcat.Concatenator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringConcat.ConcatenatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringConcat.ConcatenatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringConcat.ConcatenatorHelper.type ();
  }

}
