package CalApp;


/**
* CalApp/calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, May 29, 2023 1:17:43 PM EDT
*/

public interface calculator extends calculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calculator
