package CalApp;


/**
* CalApp/calculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, May 29, 2023 1:17:43 PM EDT
*/

public interface calculatorOperations 
{
  double addition (double x, double y);
  double subtraction (double x, double y);
  double multiplication (double x, double y);
  double division (double x, double y) throws CalApp.calculatorPackage.DivisionByZero;
  void shutdown ();
} // interface calculatorOperations
