package StringConcat;


/**
* StringConcat/Concatenator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcat.idl
* Tuesday, May 30, 2023 12:31:21 AM EDT
*/

public interface Concatenator extends ConcatenatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concatenator
