package StringReverse;


/**
* StringReverse/ReverseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Friday, 26 May, 2023 5:26:57 AM IST
*/

abstract public class ReverseHelper
{
  private static String  _id = "IDL:StringReverse/Reverse:1.0";

  public static void insert (org.omg.CORBA.Any a, StringReverse.Reverse that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StringReverse.Reverse extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StringReverse.ReverseHelper.id (), "Reverse");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StringReverse.Reverse read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReverseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StringReverse.Reverse value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StringReverse.Reverse narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringReverse.Reverse)
      return (StringReverse.Reverse)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringReverse._ReverseStub stub = new StringReverse._ReverseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StringReverse.Reverse unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StringReverse.Reverse)
      return (StringReverse.Reverse)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StringReverse._ReverseStub stub = new StringReverse._ReverseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
