package StringReverse;

/**
* StringReverse/ReverseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Friday, 26 May, 2023 5:26:57 AM IST
*/

public final class ReverseHolder implements org.omg.CORBA.portable.Streamable
{
  public StringReverse.Reverse value = null;

  public ReverseHolder ()
  {
  }

  public ReverseHolder (StringReverse.Reverse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringReverse.ReverseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringReverse.ReverseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringReverse.ReverseHelper.type ();
  }

}
