package StringReverse;


/**
* StringReverse/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Friday, 26 May, 2023 5:26:57 AM IST
*/

public interface ReverseOperations 
{
  String reverseString (String input);
} // interface ReverseOperations
