package StringConcat;


/**
* StringConcat/ConcatenatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcat.idl
* Tuesday, May 30, 2023 12:31:21 AM EDT
*/

public interface ConcatenatorOperations 
{
  String concatenate (String s1, String s2);
} // interface ConcatenatorOperations
