package StringConcat;


/**
* StringConcat/Concatenator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcat.idl
* Monday, May 29, 2023 2:10:55 PM EDT
*/

public interface Concatenator extends ConcatenatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concatenator
